##############################
# Example Simple Settings
#############################
mergeable:
  pull_requests:
    approvals: 1
    reviewers: [erickmendonca, williamgrah]

    # exclude any of the mergeable validation above. A comma separated list. For example, the following will exclude validations for approvals and label.
    exclude: 'title'

    description:
        no_empty:
            enabled: false
