---
version: 2
mergeable:
  - when: 'pull_request.open, pull_request_review.*'
    validate:
      - do: approvals
        and:
          - min:
            count: 1
          - or:
            - required:
              reviewers:
                - volksport
            - required:
              reviewers:
                - bastovall
    pass:
      - do: checks
        status: 'success'
        payload:
          title: 'Mergeable run has been completed!'
          summary: 'All checks have passed!'
    fail:
      - do: checks
        status: 'failure'
        payload:
          title: 'Mergeable run has been completed!'
          summary: 'You need at least one tech lead to review this PR.'
