---
version: 2
mergeable:
  - when: 'pull_request_review.*'
    validate:
      - do: approvals
        min:
          count: 1
        required:
          reviewers:
            - volksport
    pass:
      - do: checks
        status: 'success'
        payload:
          title: 'Mergeable run has been completed!'
          summary: 'All checks have passed!'
    fail:
      - do: checks
        status: 'failure'
        payload:
          title: 'Mergeable run has been completed!'
          summary: 'You need at least one tech lead to review this PR.'
