mergeable:
    pull_requests:
        approvals:
            min: 1
        required:
            reviewers: [mannysz, erickmendonca]
        exclude: 'description, title'
        label:
            must_exclude:
                regex: `^\\(do not merge\\)|^\\(wip\\)`
