##############################
# Example Simple Settings
#############################
mergeable:
  pull_requests:
    approvals: 1
        min: 1
        reviewers: [erickmendonca]
        message: "Cannot merge before having approvals for unit test changes."

    # exclude any of the mergeable validation above. A comma separated list. For example, the following will exclude validations for approvals and label.
    exclude: 'title'

    description:
        no_empty:
            enabled: false
